/*
 * LABELS PARA ESTADOS
 */
var statusLabel={
	'ABIERTO':'<span class="badge bg-purple">ABIERTO</span>',
	'INSCRITO':'<span class="badge bg-purple">INSCRITO</span>',
	'FORMATO PROPIO':'<span class="badge bg-purple">FORMATO PROPIO</span>',
	'SOLICITUD REGISTRADA':'<span class="badge bg-purple">SOLICITUD REGISTRADA</span>',
	'DELEGACIÓN ASIGNADA':'<span class="badge bg-purple">DELEGACIÓN ASIGNADA</span>',

	'EN MANTENIMIENTO':'<span class="badge bg-orange">EN MANTENIMIENTO</span>',
	'FORMATO ONLINE':'<span class="badge bg-orange">FORMATO ONLINE</span>',
	'SOLICITUD CONCEDIDA':'<span class="badge bg-orange">SOLICITUD CONCEDIDA</span>',
	
	'SOLICITUD AUTORIZADA':'<span class="badge bg-yellow">SOLICITUD AUTORIZADA</span>',
	'CERTIFICADO EXTERNO':'<span class="badge bg-yellow">CERTIFICADO EXTERNO</span>',
	
	'ACCION DE PERSONAL GENERADA':'<span class="badge bg-primary">ACCION DE PERSONAL GENERADA</span>',
	
	'CERTIFICADO INTERNO':'<span class="badge bg-blue">CERTIFICADO INTERNO</span>',
	'EN USO':'<span class="badge bg-blue">EN USO</span>',
	'REGISTRO MANUAL':'<span class="badge bg-blue">REGISTRO MANUAL</span>',
	'DIRECCION':'<span class="badge bg-blue">DIRECCION</span>',
	
	'CAMBIADO':'<span class="badge bg-black">CAMBIADO</span>',

	'DEROGADA':'<span class="badge bg-gray">DEROGADA</span>',
	'BAJA POR DAÑOS':'<span class="badge bg-gray">BAJA POR DAÑOS</span>',
	'INICIAL':'<span class="badge bg-gray">INICIAL</span>',
	'UNIDAD':'<span class="badge bg-gray">UNIDAD</span>',
	'BORRADOR':'<span class="badge bg-gray">BORRADOR</span>',
	'EN EDICION':'<span class="badge bg-gray">EN EDICION</span>',
	'PENDIENTE':'<span class="badge bg-gray">PENDIENTE</span>',
	'REGISTRO PENDIENTE':'<span class="badge bg-gray">REGISTRO PENDIENTE</span>',
	'NO CUMPLE':'<span class="badge bg-gray">NO CUMPLE</span>',
	'SOLICITUD GENERADA':'<span class="badge bg-gray">SOLICITUD GENERADA</span>',
	'CERTIFICADO REGISTRADO':'<span class="badge bg-gray">CERTIFICADO REGISTRADO</span>',
	'VALIDACION PENDIENTE':'<span class="badge bg-gray">VALIDACION PENDIENTE</span>',
	'GENERADO':'<span class="badge bg-gray">GENERADO</span>',

	'PLANIFICACION':'<span class="badge bg-cyan">PLANIFICACION</span>',
	'ELABORADO':'<span class="badge bg-cyan">ELABORADO</span>',
	'MANTENIMIENTO':'<span class="badge bg-cyan">MANTENIMIENTO</span>',
	'EN ESTACION':'<span class="badge bg-cyan">EN ESTACIÓN</span>',
	'INICIANDO':'<span class="badge bg-cyan">INICIANDO</span>',
	'SOLICITADO':'<span class="badge bg-cyan">SOLICITADO</span>',
	'REAGENDADA':'<span class="badge bg-cyan">REAGENDADA</span>',
	'EN REVISION':'<span class="badge bg-cyan">EN REVISION</span>',
	'REVISION':'<span class="badge bg-cyan">REVISION</span>',
	'REVISADO':'<span class="badge bg-cyan">REVISADO</span>',
	'BARRIDO':'<span class="badge bg-cyan">BARRIDO</span>',

	'EMITIDO EN CONSULTA MEDICA':'<span class="badge bg-purple">EMITIDO EN CONSULTA MEDICA</span>',
	'REGISTRO JUSTIFICADO':'<span class="badge bg-purple">REGISTRO JUSTIFICADO</span>',
	'ANTICIPO CANCELADO':'<span class="badge bg-purple">ANTICIPO CANCELADO</span>',
	'DENUNCIA DESCARTADA':'<span class="badge bg-purple">DENUNCIA DESCARTADA</span>',
	'APERTURA DE CAJA':'<span class="badge bg-purple">APERTURA DE CAJA</span>',
	'REGISTRO':'<span class="badge bg-purple">REGISTRO</span>',
	'PERMISO':'<span class="badge bg-purple">PERMISO</span>',
	'VACACIONES':'<span class="badge bg-purple">VACACIONES</span>',
	'JUBILADO':'<span class="badge bg-purple">JUBILADO</span>',
	'ENTREGADO':'<span class="badge bg-purple">ENTREGADO</span>',
	'EN CURSO':'<span class="badge bg-purple">EN CURSO</span>',
	'GENERADA':'<span class="badge bg-purple">GENERADA</span>',
	'REIMPRESO':'<span class="badge bg-purple">REIMPRESO</span>',
	'ASIGNADO':'<span class="badge bg-purple">ASIGNADO</span>',
	'INGRESADO':'<span class="badge bg-purple">INGRESADO</span>',
	'RECIBIDA':'<span class="badge bg-purple">RECIBIDA</span>',
	'CONFIRMADO':'<span class="badge bg-purple">CONFIRMADO</span>',
	'IMPRESO':'<span class="badge bg-purple">IMPRESO</span>',
	'ESTACION':'<span class="badge bg-purple">ESTACION</span>',
	'SIN INGRESO':'<span class="badge bg-purple">SIN INGRESO</span>',
	'RECIBIDO':'<span class="badge bg-purple">RECIBIDO</span>',
	'DUPLICADO':'<span class="badge bg-purple">DUPLICADO</span>',

	'ENVIADO A CORRECCION':'<span class="badge bg-maroon">ENVIADO A CORRECCION</span>',
	'REGISTRO NO JUSTIFICADO':'<span class="badge bg-maroon">REGISTRO NO JUSTIFICADO</span>',
	'SOLICITUD ANULADA':'<span class="badge bg-maroon">SOLICITUD ANULADA</span>',
	'DELEGACIÓN FINALIZADA':'<span class="badge bg-maroon">DELEGACIÓN FINALIZADA</span>',
	'INICO DE ACTIVIDAD FUERA DE ESTACION':'<span class="badge bg-maroon">INICO DE ACTIVIDAD FUERA DE ESTACION</span>',
	'ORDEN DE COBRO GENERADA':'<span class="badge bg-maroon">ORDEN DE COBRO GENERADA</span>',
	'COMISIÓN DE SERVICIOS':'<span class="badge bg-maroon">COMISIÓN DE SERVICIOS</span>',
	'COMISION DE SERVICIOS':'<span class="badge bg-maroon">COMISION DE SERVICIOS</span>',
	'SOLICITUD VALIDADA':'<span class="badge bg-maroon">SOLICITUD VALIDADA</span>',
	
	'NO APLICA':'<span class="badge bg-yellow">NO APLICA</span>',
	'RECIBIDO':'<span class="badge bg-yellow">RECIBIDO</span>',
	'PLANIFICACION':'<span class="badge bg-yellow">PLANIFICACION</span>',
	'PAUSADA':'<span class="badge bg-maroon">PAUSADA</span>',
	'EN PAUSA':'<span class="badge bg-maroon">EN PAUSA</span>',
	'EMITIDA':'<span class="badge bg-yellow">EMITIDA</span>',
	'VALIDACION':'<span class="badge bg-yellow">VALIDACION</span>',
	'NO':'<span class="badge bg-yellow">NO</span>',
	'SUSPENDIDO':'<span class="badge bg-yellow">SUSPENDIDO</span>',
	'PASIVO':'<span class="badge bg-yellow">PASIVO</span>',
	'REGISTRADO':'<span class="badge bg-yellow">REGISTRADO</span>',
	'SALIDA':'<span class="badge bg-yellow">SALIDA</span>',
	'PRIMERA CITACION':'<span class="badge bg-yellow">PRIMERA CITACION</span>',
	'MUSEO':'<span class="badge bg-yellow">MUSEO</span>',

	'REGISTRO INJUSTIFICABLE':'<span class="badge bg-red">REGISTRO INJUSTIFICABLE</span>',
	'ACCION DE PERSONAL ANULADA':'<span class="badge bg-red">ACCION DE PERSONAL ANULADA</span>',
	'SOLICITUD NEGADA':'<span class="badge bg-red">SOLICITUD NEGADA</span>',
	'ORDEN ANULADA':'<span class="badge bg-red">ORDEN ANULADA</span>',
	'ERROR':'<span class="badge bg-red">ERROR</span>',
	'PRORROGA VENCIDA':'<span class="badge bg-red">PRORROGA VENCIDA</span>',
	'DENUNCIA ENVIADA':'<span class="badge bg-red">DENUNCIA ENVIADA</span>',
	'DENUNCIA RECIBIDA':'<span class="badge bg-red">DENUNCIA RECIBIDA</span>',
	'CERTIFICADO ANULADO':'<span class="badge bg-red">CERTIFICADO ANULADO</span>',
	'REGISTRO ANULADO':'<span class="badge bg-red">REGISTRO ANULADO</span>',
	
	'INICIADA':'<span class="badge bg-red">INICIADA</span>',
	'SOLICITUD NEGADA':'<span class="badge bg-red">SOLICITUD NEGADA</span>',
	'CADUCADA':'<span class="badge bg-red">CADUCADA</span>',
	'CERRADA':'<span class="badge bg-red">CERRADA</span>',
	'ELIMINADO':'<span class="badge bg-red">ELIMINADO</span>',
	'VENCIDO':'<span class="badge bg-red">VENCIDO</span>',
	'VENCIDA':'<span class="badge bg-red">VENCIDA</span>',
	'ANULADA':'<span class="badge bg-red">ANULADA</span>',
	'AUSENTE':'<span class="badge bg-red">AUSENTE</span>',
	'CANCELADA':'<span class="badge bg-red">CANCELADA</span>',
	'CANCELADO':'<span class="badge bg-red">CANCELADO</span>',
	'CORRECCION':'<span class="badge bg-red">CORRECCION</span>',
	'SEGUNDA CITACION':'<span class="badge bg-red">SEGUNDA CITACION</span>',
	'NOTIFICADO':'<span class="badge bg-red">NOTIFICADO</span>',
	'SIN STOCK':'<span class="badge bg-red">SIN STOCK</span>',

	'BUEN ESTADO':'<span class="badge bg-green">BUEN ESTADO</span>',
	'LEIDO':'<span class="badge bg-green">LEIDO</span>',
	'TEST REALIZADA':'<span class="badge bg-green">TEST REALIZADA</span>',
	'REGISTRO JUSTIFICADO':'<span class="badge bg-green">REGISTRO JUSTIFICADO</span>',
	'PROCESADO':'<span class="badge bg-green">PROCESADO</span>',
	'REGISTRO CORRECTO':'<span class="badge bg-green">REGISTRO CORRECTO</span>',
	'SOLICITUD APROBADA':'<span class="badge bg-green">SOLICITUD APROBADA</span>',
	'SOLICITUD AUTORIZADA':'<span class="badge bg-green">SOLICITUD AUTORIZADA</span>',
	
	'EQUIPOS REPARADOS':'<span class="badge bg-green">EQUIPOS REPARADOS</span>',
	'REGISTRO COMPLETO':'<span class="badge bg-green">REGISTRO COMPLETO</span>',
	'PRORROGA APROBADA':'<span class="badge bg-green">PRORROGA APROBADA</span>',
	'DENUNCIA SOLUCIONADA':'<span class="badge bg-green">DENUNCIA SOLUCIONADA</span>',
	'FINALIZADA':'<span class="badge bg-green">FINALIZADA</span>',
	'ACTIVIDAD FINALIZADA':'<span class="badge bg-green">ACTIVIDAD FINALIZADA</span>',
	'SOLICITUD APROBADA':'<span class="badge bg-green">SOLICITUD APROBADA</span>',
	'VALIDADA':'<span class="badge bg-green">VALIDADA</span>',
	'VALIDADO':'<span class="badge bg-green">VALIDADO</span>',
	'CERTIFICADO VALIDADO':'<span class="badge bg-green">CERTIFICADO VALIDADO</span>',
	'EN FUNCIONES':'<span class="badge bg-green">EN FUNCIONES</span>',
	'A LA FECHA':'<span class="badge bg-green">A LA FECHA</span>',
	'VIGENTE':'<span class="badge bg-green">VIGENTE</span>',
	'ATENDIDO':'<span class="badge bg-green">ATENDIDO</span>',
	'FINALIZADO':'<span class="badge bg-green">FINALIZADO</span>',
	'PAGADO':'<span class="badge bg-green">PAGADO</span>',
	'SI':'<span class="badge bg-green">SI</span>',
	'ACTIVA':'<span class="badge bg-green">ACTIVA</span>',
	'ACTIVO':'<span class="badge bg-green">ACTIVO</span>',
	'OPERATIVO':'<span class="badge bg-green">OPERATIVO</span>',
	'EN FUNCIONES':'<span class="badge bg-green">EN FUNCIONES</span>',
	'EMITIDO':'<span class="badge bg-green">EMITIDO</span>',
	'IMPRESO':'<span class="badge bg-green">IMPRESO</span>',
	'DESPACHADA':'<span class="badge bg-green">DESPACHADA</span>',
	'ARCHIVADO':'<span class="badge bg-green">ARCHIVADO</span>',
	'EVALUADA':'<span class="badge bg-green">EVALUADA</span>',
	'EVALUADO':'<span class="badge bg-green">EVALUADO</span>',
	'ASISTIO':'<span class="badge bg-green">ASISTIO</span>',
	'APROBADO':'<span class="badge bg-green">APROBADO</span>',
	'REFRENDADO':'<span class="badge bg-green">REFRENDADO</span>',
	'ENTREGADO':'<span class="badge bg-green">ENTREGADO</span>',
	'CAJA CERRADA':'<span class="badge bg-green">CAJA CERRADA</span>'
};
/*
 * ESTADOS - LEYENDAS PARA FORMULARIOS Y PERMISOS
 */
var requiredLabel={
	'true':'<span class="badge bg-green">Requerido</span>',
	'false':'<span class="badge bg-yellow">Opcional</span>'
};
var preguntaTypeLabel={
	'Preguntas':'<span class="badge bg-cyan">Preguntas</span>',
	'Item':'<span class="badge bg-purple">Item</span>'
};